-- Deletamos os inserts de instrumentos
ALTER TABLE "INSTRUMENTO" DROP CONSTRAINT "FK_INSTRUMENTO_MEMBRO";
ALTER TABLE "INSTRUMENTO" 
ADD CONSTRAINT "FK_INSTRUMENTO_INST" 
FOREIGN KEY ("MEMBRO") 
REFERENCES "INSTRUMENTISTA" ("CPF_INSTRUMENTISTA") 
ON DELETE CASCADE;

INSERT INTO "INSTRUMENTISTA" ("CPF_INSTRUMENTISTA")
SELECT "CPF" FROM "MEMBRO" WHERE "EH_INSTRUMENTISTA" = 'S';

INSERT INTO "VOCALISTA" ("CPF_VOCALISTA")
SELECT "CPF" FROM "MEMBRO" WHERE "EH_VOCALISTA" = 'S';

COMMIT;

ALTER TABLE "MEMBRO" DROP (
    "EH_PRODUTOR", 
    "EH_COMPOSITOR", 
    "EH_INSTRUMENTISTA", 
    "EH_VOCALISTA"
);
-- Adicionamos os inserts novamente
COMMIT;
